
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: restaurant_db
  username: postgres
  password: admin1
  host: localhost
  port: 5432

test:
  <<: *default
  database: restaurant_db
  username: postgres
  password: admin1

production:
  <<: *default
  database: restaurant_db
  username: postgres
  password: admin1
